### ISSUE TITLE
run.py  error

### ISSUE THREAD

**Issue by zgq91** [wadimkehl/ssd-6d#1]
Hi:
   When I execute run.py the following error occurs：
   ssd-6d/rendering/utils.py", line 81
    transform[0:3, 0:3] = angle_axis @ rot
                                                   ^
   SyntaxError: invalid syntax

my environment: anaconda2, tensorflow 1.2

**Comment by wadimkehl** [comment]
That's a python2 compatibility issue. I committed a fix.

**Comment by margonotmango** [comment]
Hi:
When I excute run.py use python2, it says:
"rendering/renderer.py" line 201
proj-self.cam @ pose[0:3, 3]
syntaxError: invalid syntax
