### ISSUE TITLE
ruamel_yaml to ruamel.yaml

### ISSUE THREAD

**Issue by eyildiz-ugoe** [wadimkehl/ssd-6d#10]
`/utils/sixd.py` line 10:

```
if sys.platform == "darwin":
    import ruamel.yaml as yaml
else:
    import ruamel_yaml as yaml
```

on Ubuntu 16.04 with Python 3.5 (with indeed ruamel_yaml installed) prompts the error of:

 `ImportError: No module named 'ruamel_yaml'`

which works only when you change the above code to simply:

```
#if sys.platform == "darwin":
#    import ruamel.yaml as yaml
#else:
#    import ruamel_yaml as yaml

import ruamel.yaml as yaml
```

Just letting people know, since I wasted a lot of time on this.

**Comment by wadimkehl** [comment]
Thanks for the find!
