### ISSUE TITLE
a Problem about the result -----the 3 images 

### ISSUE THREAD

**Issue by keacifer** [wadimkehl/ssd-6d#14]
I did all the things , and the program had no error came out , but the final result  shows 3 images , in the FInal poses the blue cube seems to be on the camera, not on the object,I can only see a corner of it  , in the 2Dboxes , it seems the box is not so precise , I want to know the reason of the problem.

**Comment by wadimkehl** [comment]
Could you provide pictures? Also, as mentioned, these are not the final poses because the refinement stage is not included due to IP issues

**Comment by keacifer** [comment]
thank you very much , I fixed  it , expecting for your updating version , It's a great work. I just add CUDA_VISIBLE_DEVICES=""  before python3  run.py, to use the cpu ,and it stop showing the image again and again after I close it .and it's OK now. maybe it's something about the conda and cudnn settings.
