### ISSUE TITLE
Deep Learning of Local RGB-D Patches for 3D Object Detection  and 6D Pose Estimation

### ISSUE THREAD

**Issue by zgq91** [wadimkehl/ssd-6d#2]
Hi:
    Recently looking at your "Deep Learning of Local RGB-D Patches for 3D
Object Detection and 6D Pose Estimation" paper, where the network structure is not very clear. Is there any more detailed information?

**Comment by wadimkehl** [comment]
What exactly is not clear? There is a figure depicting the whole architecture and some text that explains every layer.

**Comment by zgq91** [comment]
@wadimkehl  input patch x(32x32x4): 4on behalf of what it means? rgb + depth this understanding is correct.What is the network output y structure?

**Comment by wadimkehl** [comment]
Since it is an autoencoder, input and output have the same shape.

**Comment by zgq91** [comment]
@wadimkehl  Can provide papers code, just look at the essay many places stumbled. If you can provide the code would be very much appreciated, my email zgqcontact@163.com.
