### ISSUE TITLE
error in rendering/renderer.py

### ISSUE THREAD

**Issue by margonotmango** [wadimkehl/ssd-6d#3]
Hi:
When I excute run.py use python2, it says:
"rendering/renderer.py" line 201
proj-self.cam @ pose[0:3, 3]
syntaxError: invalid syntax

**Comment by margonotmango** [comment]
By the way, which version of tensorflow did you use?

**Comment by margonotmango** [comment]
@wadimkehl

**Comment by wadimkehl** [comment]
Fixed. We trained, evaluated and froze the graphs with TF 1.0 but we recentyl tested with TF 1.3 and TF 1.4
